
;MARK:Key----------------------------------------------------------
[KeySwap_0]
condition = $active0 == 1
key = shift up
type = cycle
$swapkey0 = 0,1,2,3,4,5,6,

;MARK:Constants----------------------------------------------------------
[Constants]
global $active0
global persist $swapkey0 = 0


;MARK:Present----------------------------------------------------------
[Present]
post $active0 = 0


;MARK:TextureOverrideIB----------------------------------------------------------
[TextureOverride_face_IB]
hash = 5ea47a32
$active0 = 1
Resource\ZZMI\Diffuse = ref Resource_face1
if $swapkey0 == 1
Resource\ZZMI\Diffuse = ref Resource_face2
else if $swapkey0 == 2
Resource\ZZMI\Diffuse = ref Resource_face3
else if $swapkey0 == 3
Resource\ZZMI\Diffuse = ref Resource_face4
else if $swapkey0 == 4
Resource\ZZMI\Diffuse = ref Resource_face5
else if $swapkey0 == 5
Resource\ZZMI\Diffuse = ref Resource_face6
else if $swapkey0 == 6
Resource\ZZMI\Diffuse = ref Resource_face7
endif
run = CommandList\ZZMI\SetTextures


[Resource_face1]
filename = face1.dds
[Resource_face2]
filename = face2.dds
[Resource_face3]
filename = face3.dds
[Resource_face4]
filename = face4.dds
[Resource_face5]
filename = face5.dds
[Resource_face6]
filename = face6.dds
[Resource_face7]
filename = face7.dds