
;MARK:Key----------------------------------------------------------
[KeySwap_0]
condition = $active0 == 1
key = alt up
type = cycle
$swapkey0 = 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,


;MARK:Key----------------------------------------------------------
[KeySwap_1]
condition = $active0 == 1
key = shift left
type = cycle
$swapkey1 = 0,1,


;MARK:Key----------------------------------------------------------
[KeySwap_2]
condition = $active0 == 1
key = ctrl left
type = cycle
$swapkey2 = 0,1,2,3,


;MARK:Key----------------------------------------------------------
[KeySwap_3]
condition = $active0 == 1
key = ctrl right
type = cycle
$swapkey3 = 0,1,2,3,


;MARK:Key----------------------------------------------------------
[KeySwap_4]
condition = $active0 == 1
key = ctrl up
type = cycle
$swapkey4 = 0,1,

[KeySwapT]
condition = $active0 == 1
key = shift right
type = cycle
$T = 0,1,2,3,4,5,6,7

[KeySwapT5]
condition = $active0 == 1
key = 9
type = cycle
$T5 = 0,1

;MARK:Constants----------------------------------------------------------
[Constants]
global $active0
global $active1
global persist $T = 0
global persist $T5 = 0
global persist $H = 0
global persist $W = 0
global persist $swapkey0 = 0
global persist $swapkey1 = 0
global persist $swapkey2 = 0
global persist $swapkey3 = 0
global persist $swapkey4 = 0

;MARK:Present----------------------------------------------------------
[Present]
post $active0 = 0
post $active1 = 0

;MARK:TextureOverrideVertexLimitRaise----------------------------------------------------------
[TextureOverride_a633d5b7_shangban_VertexLimitRaise]
hash = dd86f5ae
override_byte_stride = 40
override_vertex_count = 47598
uav_byte_stride = 4


;MARK:TextureOverrideVertexLimitRaise----------------------------------------------------------
[TextureOverride_68f34958_waitao_VertexLimitRaise]
hash = 947f29ae
override_byte_stride = 40
override_vertex_count = 2219
uav_byte_stride = 4


;MARK:TextureOverrideVB----------------------------------------------------------
; a633d5b7 ----------------------------
[TextureOverride_VB_a633d5b7_shangban_Position]
hash = a7769c93
vb0 = Resourcea633d5b7Position
vb2 = Resourcea633d5b7Blend
handling = skip
draw = 47598, 0


[TextureOverride_VB_a633d5b7_shangban_Texcoord]
hash = bfcfb2f7
vb1 = Resourcea633d5b7Texcoord

[TextureOverride_VB_a633d5b7_shangban_Blend]
hash = 61c399b6


;MARK:TextureOverrideVB----------------------------------------------------------
; 68f34958 ----------------------------
[TextureOverride_VB_68f34958_waitao_Position]
hash = d43597aa
vb0 = Resource68f34958Position
vb2 = Resource68f34958Blend
handling = skip
draw = 2219, 0
$active1 = 1

[TextureOverride_VB_68f34958_waitao_Texcoord]
hash = 9f083955
vb1 = Resource68f34958Texcoord

[TextureOverride_VB_68f34958_waitao_Blend]
hash = 870f56b5

[TextureOverride_IB_Xiaban]
hash = 21871660
$active0 = 1

;MARK:TextureOverrideIB----------------------------------------------------------
[TextureOverride_IB_a633d5b7_shangban_Component1]
hash = a633d5b7
match_first_index = 0
handling = skip
ib = Resource_a633d5b7_Component1
Resource\ZZMI\Diffuse = ref Resource_A1
if $T == 1
Resource\ZZMI\Diffuse = ref Resource_A2
else if $T == 2
Resource\ZZMI\Diffuse = ref Resource_A3
else if $T == 3
Resource\ZZMI\Diffuse = ref Resource_A4
else if $T == 4
Resource\ZZMI\Diffuse = ref Resource_A5
else if $T == 5
Resource\ZZMI\Diffuse = ref Resource_A6
else if $T == 6
Resource\ZZMI\Diffuse = ref Resource_A7
else if $T == 7
Resource\ZZMI\Diffuse = ref Resource_A8
endif

if $T5 == 0
Resource\ZZMI\NormalMap = ref Resource_AT4
endif
if $T5 == 1
Resource\ZZMI\NormalMap = ref Resource_AT4a
endif
Resource\ZZMI\LightMap = ref Resource_AT5

if $T5 == 0
Resource\ZZMI\MaterialMap = ref Resource_AT6
endif
if $T5 == 1
Resource\ZZMI\MaterialMap = ref Resource_AT6a
endif
run = CommandList\ZZMI\SetTextures
ps-t9 = Resource_T9
run = CommandListSkinTexture
if $swapkey0 == 0
  ; [mesh:a633d5b7-1-B.003] [vertex_count:2230]
  drawindexed = 12492,0,0
endif

if $swapkey0 == 1
  ; [mesh:a633d5b7-1-B1.001] [vertex_count:2665]
  drawindexed = 9978,12492,0
  ; [mesh:a633d5b7-1-B.003] [vertex_count:2230]
  drawindexed = 12492,0,0
endif

if $swapkey0 == 2
  ; [mesh:a633d5b7-1-B2.001] [vertex_count:750]
  drawindexed = 4212,22470,0
  ; [mesh:a633d5b7-1-B.003] [vertex_count:2230]
  drawindexed = 12492,0,0
endif

if $swapkey0 == 3
  ; [mesh:a633d5b7-1-B3.001] [vertex_count:452]
  drawindexed = 2016,26682,0
  ; [mesh:a633d5b7-1-B.003] [vertex_count:2230]
  drawindexed = 12492,0,0
endif

if $swapkey0 == 4
  ; [mesh:a633d5b7-1-lingdangB1.001] [vertex_count:1154]
  drawindexed = 4908,28698,0
  ; [mesh:a633d5b7-1-B.003] [vertex_count:2230]
  drawindexed = 12492,0,0
endif

if $swapkey0 == 5
  ; [mesh:a633d5b7-1-C] [vertex_count:2230]
  drawindexed = 12492,33606,0
endif

if $swapkey0 == 6
  ; [mesh:a633d5b7-1-C1.001] [vertex_count:2665]
  drawindexed = 9978,46098,0
  ; [mesh:a633d5b7-1-C] [vertex_count:2230]
  drawindexed = 12492,33606,0
endif

if $swapkey0 == 7
  ; [mesh:a633d5b7-1-C2.001] [vertex_count:750]
  drawindexed = 4212,56076,0
  ; [mesh:a633d5b7-1-C] [vertex_count:2230]
  drawindexed = 12492,33606,0
endif

if $swapkey0 == 8
  ; [mesh:a633d5b7-1-C3.001] [vertex_count:452]
  drawindexed = 2016,60288,0
  ; [mesh:a633d5b7-1-C] [vertex_count:2230]
  drawindexed = 12492,33606,0
endif

if $swapkey0 == 9
  ; [mesh:a633d5b7-1-lingdangC1.001] [vertex_count:1154]
  drawindexed = 4908,62304,0
  ; [mesh:a633d5b7-1-C] [vertex_count:2230]
  drawindexed = 12492,33606,0
endif

if $swapkey0 == 10
  ; [mesh:a633d5b7-1-D.003] [vertex_count:2230]
  drawindexed = 12492,67212,0
endif

if $swapkey0 == 11
  ; [mesh:a633d5b7-1-D1.001] [vertex_count:2665]
  drawindexed = 9978,79704,0
  ; [mesh:a633d5b7-1-D.003] [vertex_count:2230]
  drawindexed = 12492,67212,0
endif

if $swapkey0 == 12
  ; [mesh:a633d5b7-1-D2.001] [vertex_count:750]
  drawindexed = 4212,89682,0
  ; [mesh:a633d5b7-1-D.003] [vertex_count:2230]
  drawindexed = 12492,67212,0
endif

if $swapkey0 == 13
  ; [mesh:a633d5b7-1-D3.001] [vertex_count:452]
  drawindexed = 2016,93894,0
  ; [mesh:a633d5b7-1-D.003] [vertex_count:2230]
  drawindexed = 12492,67212,0
endif

if $swapkey0 == 14
  ; [mesh:a633d5b7-1-lingdangD1.001] [vertex_count:1154]
  drawindexed = 4908,95910,0
  ; [mesh:a633d5b7-1-D.003] [vertex_count:2230]
  drawindexed = 12492,67212,0
endif

if $swapkey0 == 15
  ; [mesh:a633d5b7-1-E.003] [vertex_count:2230]
  drawindexed = 12492,100818,0
endif

if $swapkey0 == 16
  ; [mesh:a633d5b7-1-E1.001] [vertex_count:2665]
  drawindexed = 9978,113310,0
  ; [mesh:a633d5b7-1-E.003] [vertex_count:2230]
  drawindexed = 12492,100818,0
endif

if $swapkey0 == 17
  ; [mesh:a633d5b7-1-E2.001] [vertex_count:750]
  drawindexed = 4212,123288,0
  ; [mesh:a633d5b7-1-E.003] [vertex_count:2230]
  drawindexed = 12492,100818,0
endif

if $swapkey0 == 18
  ; [mesh:a633d5b7-1-E3.001] [vertex_count:452]
  drawindexed = 2016,127500,0
  ; [mesh:a633d5b7-1-E.003] [vertex_count:2230]
  drawindexed = 12492,100818,0
endif

if $swapkey0 == 19
  ; [mesh:a633d5b7-1-lingdangE1.001] [vertex_count:1154]
  drawindexed = 4908,129516,0
  ; [mesh:a633d5b7-1-E.003] [vertex_count:2230]
  drawindexed = 12492,100818,0
endif

if $swapkey1 == 0
  ; [mesh:a633d5b7-1-Yshoubi] [vertex_count:6011]
  drawindexed = 21258,134424,0
endif

if $swapkey1 == 1
  ; [mesh:a633d5b7-1-Yshoubi2] [vertex_count:2368]
  drawindexed = 10800,155682,0
endif

; [mesh:a633d5b7-1-shenti] [vertex_count:2322]
drawindexed = 11190,166482,0

if $swapkey2 == 1
  ; [mesh:a633d5b7-1-兔耳发饰.001] [vertex_count:2094]
  drawindexed = 7710,177672,0
  ; [mesh:a633d5b7-1-左护腕.001] [vertex_count:3196]
  drawindexed = 13920,185382,0
endif

if $swapkey2 == 2
  ; [mesh:a633d5b7-1-兔耳发饰.001] [vertex_count:2094]
  drawindexed = 7710,177672,0
endif

if $swapkey2 == 3
  ; [mesh:a633d5b7-1-左护腕.001] [vertex_count:3196]
  drawindexed = 13920,185382,0
endif

if $swapkey3 == 0
  ; [mesh:a633d5b7-1-Yxiangquan1] [vertex_count:1214]
  drawindexed = 3324,199302,0
  ; [mesh:a633d5b7-1-Yxiangquan2] [vertex_count:538]
  drawindexed = 2460,202626,0
endif

if $swapkey3 == 1
  ; [mesh:a633d5b7-1-Yxiangquan1] [vertex_count:1214]
  drawindexed = 3324,199302,0
endif

if $swapkey3 == 2
  ; [mesh:a633d5b7-1-项圈毛球.001] [vertex_count:401]
  drawindexed = 1296,205086,0
endif


;MARK:TextureOverrideIB----------------------------------------------------------
[TextureOverride_IB_68f34958_waitao_Component1]
hash = 68f34958
match_first_index = 0
handling = skip
ib = Resource_68f34958_Component1

if $swapkey4 == 0
  ; [mesh:68f34958-1-waitao.003] [vertex_count:2219]
  drawindexed = 8814,0,0
endif


;MARK:ResourceBuffer----------------------------------------------------------
[Resourcea633d5b7Position]
type = Buffer
stride = 40
filename = Buffer/a633d5b7-Position.buf

[Resourcea633d5b7Texcoord]
type = Buffer
stride = 20
filename = Buffer/a633d5b7-Texcoord.buf

[Resourcea633d5b7Blend]
type = Buffer
stride = 32
filename = Buffer/a633d5b7-Blend.buf

[Resource_a633d5b7_Component1]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Buffer/a633d5b7-Component1.buf


;MARK:ResourceBuffer----------------------------------------------------------
[Resource68f34958Position]
type = Buffer
stride = 40
filename = Buffer/68f34958-Position.buf

[Resource68f34958Texcoord]
type = Buffer
stride = 20
filename = Buffer/68f34958-Texcoord.buf

[Resource68f34958Blend]
type = Buffer
stride = 32
filename = Buffer/68f34958-Blend.buf

[Resource_68f34958_Component1]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Buffer/68f34958-Component1.buf


;MARK:ResourceTexture----------------------------------------------------------
[Resource_a633d5b7_1_ae109401_Slot_DiffuseMap]
filename = Texture/a633d5b7_1_ae109401_Slot_DiffuseMap.dds

[Resource_a633d5b7_1_ebac056e_Slot_NormalMap]
filename = Texture/a633d5b7_1_ebac056e_Slot_NormalMap.dds

[Resource_a633d5b7_1_3864f20c_Slot_LightMap]
filename = Texture/a633d5b7_1_3864f20c_Slot_LightMap.dds

[Resource_a633d5b7_1_d57df6aa_Slot_MaterialMap]
filename = Texture/a633d5b7_1_d57df6aa_Slot_MaterialMap.dds

[Resource_A1]
filename = Texture/A1.dds
[Resource_A2]
filename = Texture/A2.dds
[Resource_A3]
filename = Texture/A3.dds
[Resource_A4]
filename = Texture/A4.dds
[Resource_A5]
filename = Texture/A5.dds
[Resource_A6]
filename = Texture/A6.dds
[Resource_A7]
filename = Texture/A7.dds
[Resource_A8]
filename = Texture/A8.dds

[Resource_B1]
filename = Texture/B1.dds
[Resource_B2]
filename = Texture/B2.dds
[Resource_B3]
filename = Texture/B3.dds
[Resource_B4]
filename = Texture/B4.dds
[Resource_B5]
filename = Texture/B5.dds
[Resource_B6]
filename = Texture/B6.dds
[Resource_B7]
filename = Texture/B7.dds
[Resource_B8]
filename = Texture/B8.dds

[Resource_C1]
filename = Texture/C1.dds
[Resource_C2]
filename = Texture/C2.dds
[Resource_C3]
filename = Texture/C3.dds
[Resource_C4]
filename = Texture/C4.dds
[Resource_C5]
filename = Texture/C5.dds
[Resource_C6]
filename = Texture/C6.dds
[Resource_C7]
filename = Texture/C7.dds
[Resource_C8]
filename = Texture/C8.dds

[Resource_D1]
filename = Texture/D1.dds
[Resource_D2]
filename = Texture/D2.dds
[Resource_D3]
filename = Texture/D3.dds
[Resource_D4]
filename = Texture/D4.dds
[Resource_D5]
filename = Texture/D5.dds
[Resource_D6]
filename = Texture/D6.dds
[Resource_D7]
filename = Texture/D7.dds
[Resource_D8]
filename = Texture/D8.dds

[Resource_E1]
filename = Texture/E1.dds
[Resource_E2]
filename = Texture/E2.dds
[Resource_E3]
filename = Texture/E3.dds
[Resource_E4]
filename = Texture/E4.dds
[Resource_E5]
filename = Texture/E5.dds
[Resource_E6]
filename = Texture/E6.dds
[Resource_E7]
filename = Texture/E7.dds
[Resource_E8]
filename = Texture/E8.dds

[Resource_AT4]
filename = Texture/AT4.dds
[Resource_AT5]
filename = Texture/AT5.dds
[Resource_AT6]
filename = Texture/AT6.dds
[Resource_AT6a]
filename = Texture/AT6a.dds
[Resource_AT6b]
filename = Texture/AT6b.dds
[Resource_AT6c]
filename = Texture/AT6c.dds
[Resource_AT6d1]
filename = Texture/AT6d1.dds
[Resource_AT6d2]
filename = Texture/AT6d2.dds
[Resource_AT6e]
filename = Texture/AT6e.dds

[Resource_BT4]
filename = Texture/BT4.dds
[Resource_BT5]
filename = Texture/BT5.dds
[Resource_BT6]
filename = Texture/BT6.dds

[Resource_CT4]
filename = Texture/CT4.dds
[Resource_CT5]
filename = Texture/CT5.dds
[Resource_CT6]
filename = Texture/CT6.dds

[Resource_AT4a]
filename = Texture/AT4a.dds
[Resource_DT4]
filename = Texture/DT4.dds
[Resource_DT4a]
filename = Texture/DT4a.dds
[Resource_DT4b]
filename = Texture/DT4b.dds
[Resource_DT5]
filename = Texture/DT5.dds
[Resource_DT6]
filename = Texture/DT6.dds
[Resource_DT6a]
filename = Texture/DT6a.dds
[Resource_DT6b]
filename = Texture/DT6b.dds
[Resource_ET6]
filename = Texture/ET6.dds
[Resource_ET4]
filename = Texture/ET4.dds
[Resource_ET4a]
filename = Texture/ET4a.dds
[Resource_ET4b]
filename = Texture/ET4b.dds
[Resource_ET5]
filename = Texture/ET5.dds
[Resource_FT4]
filename = Texture/FT4.dds


[Resource_AT5a]
filename = Texture/AT5a.dds
[Resource_AT5b]
filename = Texture/AT5b.dds
[Resource_AT5c]
filename = Texture/AT5c.dds

[Resource_AT5S]
filename = Texture/AT5S.dds
[Resource_AT5X]
filename = Texture/AT5X.dds
[Resource_BT5S]
filename = Texture/BT5S.dds
[Resource_BT5X]
filename = Texture/BT5X.dds

[Resource_H1]
filename = Texture/H1.dds
[Resource_H2]
filename = Texture/H2.dds
[Resource_H3]
filename = Texture/H3.dds
[Resource_H4]
filename = Texture/H4.dds
[Resource_H5]
filename = Texture/H5.dds
[Resource_H6]
filename = Texture/H6.dds
[Resource_H7]
filename = Texture/H7.dds
[Resource_H8]
filename = Texture/H8.dds
[Resource_H9]
filename = Texture/H9.dds
[Resource_HT5A]
filename = Texture/HT5A.dds
[Resource_HT5B]
filename = Texture/HT5B.dds
[Resource_T9]
filename = Texture/T9.dds
[Resource_T8]
filename = Texture/T8.dds
[Resource_T10]
filename = Texture/T10.dds
[Resource_T11]
filename = Texture/T11.dds
[Resource_T12]
filename = Texture/T12.dds
;sha256=14830d2b36048d3c3a8facb00744de40890c89859c0a6002552ea85b7791aba1

