[KeySwapH]
condition = $active0 == 1
key = 0
type = cycle
$H = 0,1

[Constants]
global $active0
global $active1
global $active2
global persist $T = 0
global persist $T5 = 0
global persist $H = 0
global persist $W = 0

[Present]
post $active0 = 0
post $active1 = 0
post $active2 = 0


;MARK:TextureOverrideVertexLimitRaise----------------------------------------------------------
[TextureOverride_6cca89ab_toufa_VertexLimitRaise]
hash = 2d4c7c18
override_byte_stride = 40
override_vertex_count = 7232
uav_byte_stride = 4


;MARK:TextureOverrideVB----------------------------------------------------------
; 6cca89ab ----------------------------
[TextureOverride_VB_6cca89ab_toufa_Position]
hash = 35096cb6
vb0 = Resource6cca89abPosition
vb2 = Resource6cca89abBlend
handling = skip
draw = 7232, 0

[TextureOverride_VB_6cca89ab_toufa_Texcoord]
hash = 9c0aad96
vb1 = Resource6cca89abTexcoord

[TextureOverride_VB_6cca89ab_toufa_Blend]
hash = 5a263750


;MARK:TextureOverrideIB----------------------------------------------------------
[TextureOverride_IB_6cca89ab_toufa_Component1]
hash = 6cca89ab
match_first_index = 0
handling = skip
$active0 = 1
ib = Resource_6cca89ab_Component1
if $H == 1
Resource\ZZMI\Diffuse = ref Resource_H2
endif
run = CommandList\ZZMI\SetTextures

; [mesh:6cca89ab-1-toufa] [vertex_count:5735]
drawindexed = 23427,0,0

[TextureOverride_IB_6cca89ab_toufa_Component2]
hash = 6cca89ab
match_first_index = 23427
handling = skip
ib = Resource_6cca89ab_Component2
if $H == 1
Resource\ZZMI\Diffuse = ref Resource_H2
endif
run = CommandList\ZZMI\SetTextures

; [mesh:6cca89ab-2-toufa] [vertex_count:1497]
drawindexed = 6120,0,0


;MARK:ResourceBuffer----------------------------------------------------------
[Resource6cca89abPosition]
type = Buffer
stride = 40
filename = Buffer/6cca89ab-Position.buf

[Resource6cca89abTexcoord]
type = Buffer
stride = 20
filename = Buffer/6cca89ab-Texcoord.buf

[Resource6cca89abBlend]
type = Buffer
stride = 32
filename = Buffer/6cca89ab-Blend.buf

[Resource_6cca89ab_Component1]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Buffer/6cca89ab-Component1.buf

[Resource_6cca89ab_Component2]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Buffer/6cca89ab-Component2.buf


;MARK:ResourceTexture----------------------------------------------------------
[Resource_6cca89ab_1_c96de436_Slot_DiffuseMap]
filename = Texture/6cca89ab_1_c96de436_Slot_DiffuseMap.dds

[Resource_A1]
filename = Texture/A1.dds
[Resource_A2]
filename = Texture/A2.dds
[Resource_A3]
filename = Texture/A3.dds
[Resource_A4]
filename = Texture/A4.dds
[Resource_A5]
filename = Texture/A5.dds
[Resource_A6]
filename = Texture/A6.dds
[Resource_A7]
filename = Texture/A7.dds
[Resource_A8]
filename = Texture/A8.dds

[Resource_B1]
filename = Texture/B1.dds
[Resource_B2]
filename = Texture/B2.dds
[Resource_B3]
filename = Texture/B3.dds
[Resource_B4]
filename = Texture/B4.dds
[Resource_B5]
filename = Texture/B5.dds
[Resource_B6]
filename = Texture/B6.dds
[Resource_B7]
filename = Texture/B7.dds
[Resource_B8]
filename = Texture/B8.dds

[Resource_C1]
filename = Texture/C1.dds
[Resource_C2]
filename = Texture/C2.dds
[Resource_C3]
filename = Texture/C3.dds
[Resource_C4]
filename = Texture/C4.dds
[Resource_C5]
filename = Texture/C5.dds
[Resource_C6]
filename = Texture/C6.dds
[Resource_C7]
filename = Texture/C7.dds
[Resource_C8]
filename = Texture/C8.dds

[Resource_D1]
filename = Texture/D1.dds
[Resource_D2]
filename = Texture/D2.dds
[Resource_D3]
filename = Texture/D3.dds
[Resource_D4]
filename = Texture/D4.dds
[Resource_D5]
filename = Texture/D5.dds
[Resource_D6]
filename = Texture/D6.dds
[Resource_D7]
filename = Texture/D7.dds
[Resource_D8]
filename = Texture/D8.dds

[Resource_E1]
filename = Texture/E1.dds
[Resource_E2]
filename = Texture/E2.dds
[Resource_E3]
filename = Texture/E3.dds
[Resource_E4]
filename = Texture/E4.dds
[Resource_E5]
filename = Texture/E5.dds
[Resource_E6]
filename = Texture/E6.dds
[Resource_E7]
filename = Texture/E7.dds
[Resource_E8]
filename = Texture/E8.dds

[Resource_AT4]
filename = Texture/AT4.dds
[Resource_AT5]
filename = Texture/AT5.dds
[Resource_AT6]
filename = Texture/AT6.dds
[Resource_AT6a]
filename = Texture/AT6a.dds
[Resource_AT6b]
filename = Texture/AT6b.dds
[Resource_AT6c]
filename = Texture/AT6c.dds
[Resource_AT6d1]
filename = Texture/AT6d1.dds
[Resource_AT6d2]
filename = Texture/AT6d2.dds
[Resource_AT6e]
filename = Texture/AT6e.dds

[Resource_BT4]
filename = Texture/BT4.dds
[Resource_BT5]
filename = Texture/BT5.dds
[Resource_BT6]
filename = Texture/BT6.dds

[Resource_CT4]
filename = Texture/CT4.dds
[Resource_CT5]
filename = Texture/CT5.dds
[Resource_CT6]
filename = Texture/CT6.dds

[Resource_DT4]
filename = Texture/DT4.dds
[Resource_DT4a]
filename = Texture/DT4a.dds
[Resource_DT4b]
filename = Texture/DT4b.dds
[Resource_DT5]
filename = Texture/DT5.dds
[Resource_DT6]
filename = Texture/DT6.dds
[Resource_DT6a]
filename = Texture/DT6a.dds
[Resource_DT6b]
filename = Texture/DT6b.dds
[Resource_ET6]
filename = Texture/ET6.dds
[Resource_ET4]
filename = Texture/ET4.dds
[Resource_ET4a]
filename = Texture/ET4a.dds
[Resource_ET4b]
filename = Texture/ET4b.dds
[Resource_ET5]
filename = Texture/ET5.dds
[Resource_FT4]
filename = Texture/FT4.dds


[Resource_AT5a]
filename = Texture/AT5a.dds
[Resource_AT5b]
filename = Texture/AT5b.dds
[Resource_AT5c]
filename = Texture/AT5c.dds

[Resource_AT5S]
filename = Texture/AT5S.dds
[Resource_AT5X]
filename = Texture/AT5X.dds
[Resource_BT5S]
filename = Texture/BT5S.dds
[Resource_BT5X]
filename = Texture/BT5X.dds

[Resource_H1]
filename = Texture/H1.dds
[Resource_H2]
filename = Texture/H2.dds
[Resource_H3]
filename = Texture/H3.dds
[Resource_H4]
filename = Texture/H4.dds
[Resource_H5]
filename = Texture/H5.dds
[Resource_H6]
filename = Texture/H6.dds
[Resource_H7]
filename = Texture/H7.dds
[Resource_H8]
filename = Texture/H8.dds
[Resource_H9]
filename = Texture/H9.dds
[Resource_HT5A]
filename = Texture/HT5A.dds
[Resource_HT5B]
filename = Texture/HT5B.dds
[Resource_T9]
filename = Texture/T9.dds
[Resource_T8]
filename = Texture/T8.dds
[Resource_T10]
filename = Texture/T10.dds
[Resource_T11]
filename = Texture/T11.dds
[Resource_T12]
filename = Texture/T12.dds


;sha256=00990e368f5264d64fed80b481729b90f878fbdcdf08136221f41b80aa9f0db0

